accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('main/', views.main_view, name='main'),
    path('register/', views.register_view, name='register'),
    path('forgot/', views.forgot_view, name='forgot'),
]

innercalm/urls.py
# main urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),  # Include website URLs
    path('accounts/', include('accounts.urls')),  # Include accounts URLs
    path('admin_portal/', include('admin_portal.urls')),
    path('clients_portal/', include('clients_portal.urls')),  # Add a trailing slash here
    path('counselors_portal/', include('counselors_portal.urls')),

]


    # Add URLs for other apps here
    # path('admin-portal/', include('admin_portal.urls')),

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('counselors/', views.counselors, name='counselors'),
    path('indcounseling/', views.indcounseling, name='indcounseling'),
    path('gtsessions/', views.gtsessions, name='gtsessions'),
    path('onlinecounseling/', views.onlinecounseling, name='onlinecounseling'),
    path('anxietyquiz/', views.anxietyquiz, name='anxietyquiz'),
    path('contentrecommend/', views.contentrecommend, name='contentrecommend'),
    path('services/', views.services, name='services'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),

]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render, redirect
from accounts.models import Counselor,Appointments,User


def home(request):
    return render(request, 'website/home.html')

def about(request):
    return render(request, 'website/about.html')

def counselors(request):
    counselors = Counselor.objects.all()  # Retrieve all counselors from the database

    return render(request, 'website/counselors.html', {'counselors': counselors})

def services(request):
    return render(request, 'website/services.html')
    
def indcounseling(request):
    return render(request, 'website/indcounseling.html')

def gtsessions(request):
    return render(request, 'website/gtsessions.html')

def onlinecounseling(request):
    return render(request, 'website/onlinecounseling.html')

def anxietyquiz(request):
    return render(request, 'website/anxietyquiz.html')

def contentrecommend(request):
    return render(request, 'website/contentrecommend.html')

def portfolio(request):
    return render(request, 'website/portfolio.html')

def contact(request):
    return render(request, 'website/contact.html')




# def take_appointments(request):
#     if request.method=='POST':
#         p_name=request.POST.get('p_name')
#         p_contact=request.POST.get('p_contact')
#         counselor=request.POST.get('counselor')
#         client=request.user
#         user=User.objects.get(id=counselor)
#         reason=request.POST.get('reason')
#         duration=request.POST.get('duration')
#         type=request.POST.get('a_type')
#         time=request.POST.get('time')
#         date=request.POST.get('date')
#         status='Scheduled'
#         Appointments.objects.create(p_name=p_name,p_contact=p_contact,counselor=user,client=client,  reason=reason,duration=duration,type=type,time=time,date=date,status=status)
        
#         return render(request, 'website/home.html')
#     data=User.objects.filter(is_doc=True)
#     return render(request, 'website/home.html',{'data':data})

website/templates/website/anxietyquiz.html
<!-- website/templates/website/home.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anxiety Quiz || InnerCalm</title>


    <!-- Favicons -->

    <link rel="stylesheet" href="{% static 'website/img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'website/img/apple-touch-icon.png' %}" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'website/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}">

    <!-- Template Main CSS File -->

    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">
</head>

<body>


    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-flex align-items-center fixed-top">
        <div class="container d-flex justify-content-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope"></i> <a href="mailto:contact@innercalm.com">contact@innercalm.com</a>
                <i class="bi bi-phone"></i> +92 340 1417862
            </div>
            <div class="d-none d-lg-flex social-links align-items-center">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto">
                <a href="{% url 'website:home' %}" class="logo me-auto">
                    <img src="{% static 'website/img/blacklogo2.png' %}" alt="" class="img-fluid">
                </a>
            </h1>

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto" href="{% url 'website:home' %}hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'website:about' %}">About</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'website:counselors' %}">Counselors</a></li>
                    <li class="dropdown">
                        <a href="{% url 'website:services' %}"><span>Services</span> <i
                                class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="{% url 'website:indcounseling' %}">Individual Counseling</a></li>
                            <li class="dropdown">
                                <a href="{% url 'website:gtsessions' %}"><span>Group Therapy Sessions</span> <i
                                        class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="{% url 'website:gtsessions' %}">Cognitive Behavioral Therapy (CBT)</a>
                                    </li>
                                    <li><a href="{% url 'website:gtsessions' %}">Mindfulness Meditation</a></li>
                                    <li><a href="{% url 'website:gtsessions' %}">Stress Management Workshops</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'website:onlinecounseling' %}">Online Counseling</a></li>
                            <li><a href="{% url 'website:anxietyquiz' %}">Anxiety Quiz</a></li>
                            <li><a href="{% url 'website:contentrecommend' %}">Content Recommendations</a></li>
                        </ul>
                    </li>

                    <li><a class="nav-link scrollto" href="{% url 'website:contact' %}">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            <a href="{% url 'accounts:login' %}" class="appointment-btn scrollto"><span
                    class="d-none d-md-inline">Login</a>

        </div>
    </header><!-- End Header -->

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">

            <div class="d-flex justify-content-between align-items-center">
                <h2>Anxiety Quiz</h2>
                <ol>
                    <li><a href="{% url 'website:home' %}">Home</a></li>
                    <li>Anxiety Quiz</li>
                </ol>
            </div>

        </div>
    </section><!-- End Breadcrumbs Section -->

    <section class="inner-page">
        <div class="container">
            <p>
                Example inner page template
            </p>
        </div>
    </section>

    <!-- More sections for services, portfolio, etc. -->

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h1 class="flogo me-auto">
                            <a href="{% url 'website:home' %}" class="flogo me-auto">
                                <img src="{% static 'website/img/blacklogo2.png' %}" alt="" class="img-fluid">
                            </a>
                        </h1>
                        <p>
                            Comsats University Islamabad <br> Wah Campus
                            Wah Cantt, Pakistan <br><br>
                            <strong>Phone:</strong> +92 340 1417862<br>
                            <strong>Email:</strong> info@innercalm.com<br>
                        </p>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:home' %}">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:about' %}">About us</a>
                            </li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:services' %}">Services</a>
                            </li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:contact' %}">Contact Us</a>
                            </li>

                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Counseling Sessions
                                </a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                   Anxiety Quizzes
                                </a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Community Support
                                </a>
                            </li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Content Recommendations
                                </a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Resource Management
                                </a></li>
                        </ul>
                    </div>


                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Location</h4>
                        <iframe style="border:0; width: 100%; height: 200px;"
                            src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13270.495268940069!2d72.7866556!3d33.7445424!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38dfa6bc26bfa2db%3A0x2344c019578abeac!2sCOMSATS%20University%20Islamabad%2C%20Wah%20Campus!5e0!3m2!1sen!2s!4v1711169618130!5m2!1sen!2s"
                            frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>InnerCalm</span></strong>. All Rights Reserved
                </div>
            </div>
            <div class="social-links text-center text-md-right pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>


    <script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'website/js/main.js' %}"></script>
</body>

</html>

website/templates/website/contentrecommend.html
<!-- website/templates/website/home.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Content Recommendations || InnerCalm</title>


    <!-- Favicons -->

    <link rel="stylesheet" href="{% static 'website/img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'website/img/apple-touch-icon.png' %}" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'website/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}">

    <!-- Template Main CSS File -->

    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">
</head>

<body>


    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-flex align-items-center fixed-top">
        <div class="container d-flex justify-content-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope"></i> <a href="mailto:contact@innercalm.com">contact@innercalm.com</a>
                <i class="bi bi-phone"></i> +92 340 1417862
            </div>
            <div class="d-none d-lg-flex social-links align-items-center">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto">
                <a href="{% url 'website:home' %}" class="logo me-auto">
                    <img src="{% static 'website/img/blacklogo2.png' %}" alt="" class="img-fluid">
                </a>
            </h1>

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto" href="{% url 'website:home' %}hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'website:about' %}">About</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'website:counselors' %}">Counselors</a></li>
                    <li class="dropdown">
                        <a href="{% url 'website:services' %}"><span>Services</span> <i
                                class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="{% url 'website:indcounseling' %}">Individual Counseling</a></li>
                            <li class="dropdown">
                                <a href="{% url 'website:gtsessions' %}"><span>Group Therapy Sessions</span> <i
                                        class="bi bi-chevron-right"></i></a>
                                <ul>
                                    <li><a href="{% url 'website:gtsessions' %}">Cognitive Behavioral Therapy (CBT)</a>
                                    </li>
                                    <li><a href="{% url 'website:gtsessions' %}">Mindfulness Meditation</a></li>
                                    <li><a href="{% url 'website:gtsessions' %}">Stress Management Workshops</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'website:onlinecounseling' %}">Online Counseling</a></li>
                            <li><a href="{% url 'website:anxietyquiz' %}">Anxiety Quiz</a></li>
                            <li><a href="{% url 'website:contentrecommend' %}">Content Recommendations</a></li>
                        </ul>
                    </li>

                    <li><a class="nav-link scrollto" href="{% url 'website:contact' %}">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            <a href="{% url 'accounts:login' %}" class="appointment-btn scrollto"><span
                    class="d-none d-md-inline">Login</a>

        </div>
    </header><!-- End Header -->

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">

            <div class="d-flex justify-content-between align-items-center">
                <h2>Content Recommendations</h2>
                <ol>
                    <li><a href="{% url 'website:home' %}">Home</a></li>
                    <li>Content Recommendations</li>
                </ol>
            </div>

        </div>
    </section><!-- End Breadcrumbs Section -->

    <section class="inner-page">
        <div class="container">
            <p>
                Example inner page template
            </p>
        </div>
    </section>

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h1 class="flogo me-auto">
                            <a href="{% url 'website:home' %}" class="flogo me-auto">
                                <img src="{% static 'website/img/blacklogo2.png' %}" alt="" class="img-fluid">
                            </a>
                        </h1>
                        <p>
                            Comsats University Islamabad <br> Wah Campus
                            Wah Cantt, Pakistan <br><br>
                            <strong>Phone:</strong> +92 340 1417862<br>
                            <strong>Email:</strong> info@innercalm.com<br>
                        </p>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:home' %}">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:about' %}">About us</a>
                            </li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:services' %}">Services</a>
                            </li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:contact' %}">Contact Us</a>
                            </li>

                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Counseling Sessions
                                </a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Anxiety Quizzes
                                </a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Community Support
                                </a>
                            </li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Content Recommendations
                                </a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="{% url 'accounts:login' %}">
                                    Resource Management
                                </a></li>
                        </ul>
                    </div>


                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Location</h4>
                        <iframe style="border:0; width: 100%; height: 200px;"
                            src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13270.495268940069!2d72.7866556!3d33.7445424!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38dfa6bc26bfa2db%3A0x2344c019578abeac!2sCOMSATS%20University%20Islamabad%2C%20Wah%20Campus!5e0!3m2!1sen!2s!4v1711169618130!5m2!1sen!2s"
                            frameborder="0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>InnerCalm</span></strong>. All Rights Reserved
                </div>
            </div>
            <div class="social-links text-center text-md-right pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'website/js/main.js' %}"></script>
</body>

</html>