accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('main/', views.main_view, name='main'),
    path('register/', views.register_view, name='register'),
    path('forgot/', views.forgot_view, name='forgot'),
]

admin_portal/urls.py
from django.urls import path
from . import views

app_name = 'admin_portal'

urlpatterns = [
    path('home/', views.admin_home, name='home'),
    path('alluser/', views.all_users, name='alluser'),
    path('allappointments/', views.all_appointments, name='allappointments'),
    path('allcounselors/', views.all_counselors, name='allcounselors'),
    path('addcounselors/', views.add_counselors, name='addcounselors'),
    path('store_counselor/', views.store_counselor, name='store_counselor'),
    path('delete_counselor/<int:id>/', views.delete_counselor, name='delete_counselor'),
    path('allresources/', views.all_resources, name='allresources'),
    path('viewanalytics/', views.view_analytics, name='viewanalytics'),
    path('allreports/', views.all_report, name='allreports'),
    path('settings/', views.view_settings, name='settings'), 
    # Add more URL patterns as needed
    path('form_index', views.home, name='form_index'),
    path('user-post/', views.userPost, name='user-post'),
    path('topic/<int:pk>/', views.postTopic, name='topic-detail'),
    path('search-result/', views.searchView, name='search-result'),
    path('user-dashboard/', views.userDashboard, name='user-dashboard'),
    path('upvote/', views.upvote, name='upvote'),
    path('downvote/', views.downvote, name='downvote'),
    path('blog/', views.blogListView, name='blog'),
    path('article/<slug:slug>/', views.blogDetailView, name='article-detail'),
]

clients_portal/urls.py
# clients_portal/urls.py

from django.urls import path
from . import views

app_name = 'clients_portal'

urlpatterns = [
    path('login/', views.clients_login, name='login'),
    path('home/', views.clients_home, name='home'),
    path('viewquiz/', views.view_quiz, name='viewquiz'),
    path('takequiz/', views.take_quiz, name='takequiz'),
    path('takeappointments/', views.take_appointments, name='takeappointments'),
    path('viewappointments/', views.view_appointments, name='viewappointments'),
    path('viewchatbot/', views.chat, name='viewchatbot'),
    path("viewchatbot2", views.chat, name="viewchatbot2"),
    path("ask_question/", views.ask_question, name="ask_question"),
    path("meeting/", views.view_meet, name="meeting"),
    path('viewrecommendations/', views.view_recommendations, name='viewrecommendations'),
    path('allcounselors/', views.all_counselors, name='allcounselors'),
    path('allcounselors/', views.view_payment, name='allcounselors'),
    path('settings/', views.view_settings, name='settings'),
    path('delete_appoint/<int:id>/', views.delete_appoints, name='delete_appoint'),

    # Add more URL patterns as needed
    
    # API
    path('get_user_data/<int:userId>', views.get_user_data, name='get_user_data'),
    path('api/stress_level/', views.stress_level, name='stress_level'),
    path('store_ratings/',views.store_ratings,name='store_ratings'),
    path('api/appointments/', views.appointments_data, name='appointments_data')
]

counselors_portal/urls.py
# clients_portal/urls.py

from django.urls import path
from . import views

app_name = 'counselors_portal'

urlpatterns = [
    path('home/', views.counselors_home, name='home'),
    path('login/', views.login_view, name='login'),
    path('viewlogin/', views.counselors_viewlogin, name='viewlogin'),
    path('allquiz/', views.all_quiz, name='allquiz'),
    path('allappointments/', views.all_appointments, name='allappointments'),
    path('allfeedback/', views.all_feedback, name='allfeedback'),
    path('addquiz/', views.add_quiz, name='addquiz'),
    path('allresources/', views.all_resources, name='allresources'),
    path('addresources/', views.add_resources, name='addresources'),
    path('settings/', views.view_settings, name='settings'),
    path('edit_appoint/<int:id>', views.edit_appoint, name='edit_appoint'),
    path('api/counselor_appointments/', views.counselor_appointments_data, name='counselor_appointments_data'),
    # Add more URL patterns as needed
]

innercalm/urls.py
# main urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),  # Include website URLs
    path('accounts/', include('accounts.urls')),  # Include accounts URLs
    path('admin_portal/', include('admin_portal.urls')),
    path('clients_portal/', include('clients_portal.urls')),  # Add a trailing slash here
    path('counselors_portal/', include('counselors_portal.urls')),

]


    # Add URLs for other apps here
    # path('admin-portal/', include('admin_portal.urls')),

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('counselors/', views.counselors, name='counselors'),
    path('indcounseling/', views.indcounseling, name='indcounseling'),
    path('gtsessions/', views.gtsessions, name='gtsessions'),
    path('onlinecounseling/', views.onlinecounseling, name='onlinecounseling'),
    path('anxietyquiz/', views.anxietyquiz, name='anxietyquiz'),
    path('contentrecommend/', views.contentrecommend, name='contentrecommend'),
    path('services/', views.services, name='services'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),

]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserRegistrationForm(UserCreationForm):
    # Add any additional fields or customization here if needed
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class RegisterForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'}))
    password = forms.CharField(label='Password', max_length=100, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}))
    email = forms.EmailField(label='Email Address', max_length=100, required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}))

accounts/views.py
from django.shortcuts import render, redirect,reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import UserRegistrationForm,RegisterForm
from .models import Client, Counselor, User,Author,ChatBot
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
import datetime
from django.contrib.auth.signals import user_logged_in
from django.core.mail import send_mail
from django.dispatch import receiver
from django.utils.html import format_html
from django.utils.timezone import now
import google.generativeai as genai
from django.http import HttpResponseRedirect, JsonResponse

genai.configure(api_key="AIzaSyDtJeLR9T2L9P2ZCVO49j9SDWbFquFK_dI")

def ask_question(request):
    if request.method == "POST":
        text = request.POST.get("text")
        model = genai.GenerativeModel("gemini-pro")
        chat = model.start_chat()
        response = chat.send_message(text)
        user = request.user
        ChatBot.objects.create(text_input=text, gemini_output=response.text, user=user)
        # Extract necessary data from response
        response_data = {
            "text": response.text,  # Assuming response.text contains the relevant response data
            # Add other relevant data from response if needed
        }
        return JsonResponse({"data": response_data})
    else:
        return HttpResponseRedirect(
            reverse("chat")
        )

def chat(request):
    user = request.user
    chats = ChatBot.objects.filter(user=user)
    return render(request, "chat_bot.html", {"chats": chats})

def send_login_email(user):
    subject = 'Login Notification'
    login_time = now().strftime('%Y-%m-%d %H:%M:%S')
    message = format_html(
        '''
        <p>Dear {},</p>
        <p>You have successfully logged into the system on <strong>{}</strong>.</p>
        <p>If this was not you, please contact our support immediately.</p>
        <p>Best regards,</p>
        <p>InnerCalm.com</p>
        ''', user.username, login_time
    )

    send_mail(
        subject,
        message,
        'no-reply@example.com',
        [user.email],
        html_message=message,
        fail_silently=False,
    )
def send_signup_email(user):
    subject = 'Login Notification'
    login_time = now().strftime('%Y-%m-%d %H:%M:%S')
    message = format_html(
        '''
        <p>Dear {},</p>
        <p>You have successfully registered into the system on <strong>{}</strong>.</p>
        <p>If this was not you, please contact our support immediately.</p>
        <p>Best regards,</p>
        <p>InnerCalm.com</p>
        ''', user.username, login_time
    )
    send_mail(
        subject,
        message,
        'no-reply@example.com',
        [user.email],
        html_message=message,
        fail_silently=False,
    )

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        # print(user)
        if user is not None:
            login(request, user)
            send_login_email(user)
            if user.is_superuser:
                return redirect('admin_portal:home')
            elif user.is_client:
                print(user)
                return redirect('clients_portal:home')
            elif user.is_doc:
                return redirect('counselors_portal:home')
        else:
            messages.error(request, 'Invalid username or password.')
            return render(request, 'accounts/login.html')
    return render(request, 'accounts/login.html')


def logout_view(request):
    logout(request)
    return redirect('website:home')


def forgot_view(request):
    return render(request, 'accounts/forgot.html')

def main_view(request):
    return render(request, 'accounts/main.html')

# def register_view(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         raw_password = request.POST.get('password')
#         email = request.POST.get('email')
#         password = raw_password
#         user = User.objects.create_user(
#             username=username,
#             password=password,
#             email=email,
#             is_client=True
#         )
#         return redirect('accounts:login')
#     else:
#         return render(request, 'accounts/register.html')

def register_view(request):
    if request.method == 'POST':
        print("Ce")
        form = RegisterForm(request.POST)
        if form.is_valid():
            print("Ce2")
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            user = User.objects.create_user(
            username=username,
            password=password,
            email=email,
            is_client=True
            )
            user.save()
            author_inst=Author.objects.create(
                user=user
            )
            author_inst.save()
            send_signup_email(user)
            return redirect('accounts:login') 
        else:
            print(form.errors)
    else:
        form = RegisterForm()
        return render(request, 'accounts/register.html', {'form': form})

accounts/templates/accounts/forgot.html
<!-- website/templates/website/home.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot - InnerCalm</title>


    <!-- Favicons -->

    <link rel="stylesheet" href="{% static 'website/img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'website/img/apple-touch-icon.png' %}" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'website/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}">

    <!-- Template Main CSS File -->

    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">


    <style>
        .bg {
            background-color: #f8f9fa;
        }

        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>

<body>
    <div class="my-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card shadow-lg">
                        <div class="card-body p-md-5">
                            <div class="">
                                <div class="row align-items-center">
                                    <div class="col-12 col-sm-12 col-md-5 col-lg-6">
                                        <div class="">
                                            <div class="text-center">
                                                <img src="{% static 'website/img/logowhite2.png' %}" alt="Logo"
                                                    class="img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-7 col-lg-6">
                                        <div class="border shadow-lg p-lg-5 p-3 rounded">
                                            <h2 class="text-center mb-4">Forgot Password</h2>
                                            <form>
                                                <div class="mb-3">
                                                    <label for="email" class="form-label">Email Address</label>
                                                    <input type="email" id="email" class="form-control"
                                                        placeholder="Enter your email" required>
                                                </div>
                                                <div class="text-center">
                                                    <button type="submit" class="btn btn-primary w-100">Reset
                                                        Password</button>
                                                </div>
                                                <p class="mt-3 text-center">Don't have an account? <a
                                                    href="{% url 'accounts:register' %}"
                                                    class="text-decoration-none">Sign Up</a></p>
                                            <p class="mt-3 text-center">Do you check? <a
                                                    href="{% url 'clients_portal:home' %}"
                                                    class="text-decoration-none">Client Panel</a></p>
                                            <p class="mt-3 text-center">Do you check? <a
                                                    href="{% url 'admin_portal:home' %}"
                                                    class="text-decoration-none">Admin Panel</a></p>
                                            <p class="mt-3 text-center">Do you check? <a
                                                    href="{% url 'counselors_portal:home' %}"
                                                    class="text-decoration-none">Counselor Panel</a></p>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'website/js/main.js' %}"></script>
</body>

</html>

accounts/templates/accounts/login.html
<!-- website/templates/website/home.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign-In - InnerCalm</title>


    <!-- Favicons -->

    <link rel="stylesheet" href="{% static 'website/img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'website/img/apple-touch-icon.png' %}" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'website/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}">

    <!-- Template Main CSS File -->

    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">


    <style>
        .bg {
            background-color: #f8f9fa;
        }

        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>

<body>



    <div class="my-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card shadow-lg">
                        <div class="card-body p-md-5">
                            <div class="">
                                <div class="row align-items-center">
                                    <div class="col-12 col-sm-12 col-md-5 col-lg-6">
                                        <div class="">
                                            <div class="text-center">
                                                <img src="{% static 'website/img/logowhite2.png' %}" alt="Logo"
                                                    class="img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-7 col-lg-6">
                                        <div class="border shadow-lg p-lg-5 p-3 rounded">
                                            <h2 class="text-center">Login</h2>
                                            <form role="form" method="post" action="">
                                                {% csrf_token %}
                                                <div class="mb-3">
                                                    <label for="username" class="form-label">Username</label>
                                                    <input type="text" id="username" name="username" class="form-control"
                                                        placeholder="Enter your username" required>
                                                </div>
                                                <div class="mb-3">
                                                    <label for="password" class="form-label">Password</label>
                                                    <input type="password" id="password" name="password" class="form-control"
                                                        placeholder="Enter your password" required>
                                                </div>
                                                <div class="d-flex align-items-center justify-content-between">
                                                    <div class="mb-3 form-check">
                                                        <input type="checkbox" class="form-check-input" id="rememberMe">
                                                        <label class="form-check-label" for="rememberMe">Remember
                                                            Me</label>
                                                    </div>
                                                    <div class="text-end mb-3">
                                                        <a href="{% url 'accounts:forgot' %}"
                                                            class="text-decoration-none">Forgot
                                                            Password?</a>
                                                    </div>
                                                </div>
                                                <div class="text-center">
                                                    <button type="submit"
                                                        class="btn btn-primary w-100 rounded">Login</button>
                                                </div>
                                                <p class="mt-3 text-center">Don't have an account? <a
                                                        href="{% url 'accounts:register' %}"
                                                        class="text-decoration-none">Sign Up</a></p>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'website/js/main.js' %}"></script>
</body>

</html>

accounts/templates/accounts/logout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
    <!-- Add your CSS links here -->
    <link rel="stylesheet" href="{% static 'accounts/css/styles.css' %}">
</head>

<body>
    <div class="container">
        <h1>Logout</h1>
        <p>You have been successfully logged out.</p>
        <p>Return to <a href="{% url 'website:home' %}">Homepage</a></p>
    </div>
    <!-- Add your JavaScript links here -->
    <script src="{% static 'accounts/js/script.js' %}"></script>
</body>

</html>

accounts/templates/accounts/main.html
<!-- website/templates/website/home.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main - InnerCalm</title>


    <!-- Favicons -->

    <link rel="stylesheet" href="{% static 'website/img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'website/img/apple-touch-icon.png' %}" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'website/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}">

    <!-- Template Main CSS File -->

    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">


    <style>
        .bg {
            background-color: #f8f9fa;
        }

        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>

<body>



    <div class="my-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card shadow-lg">
                        <div class="card-body p-md-5">
                            <div class="">
                                <div class="row align-items-center">
                                    <div class="col-12 col-sm-12 col-md-5 col-lg-6">
                                        <div class="">
                                            <div class="text-center">
                                                <img src="{% static 'website/img/logowhite2.png' %}" alt="Logo"
                                                    class="img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-7 col-lg-6">
                                        <div class="border shadow-lg p-lg-5 p-3 rounded">
                                            <h2 class="text-center">Login Here</h2>
                                            <div class="row justify-content-center align-items-center my-5">
                                                <div class="col-4">
                                                    <div class="text-center">
                                                        <a href="{% url 'accounts:login' %}"
                                                            class="appointment-btn w-100">As
                                                            Client</a>
                                                    </div>
                                                </div>
                                                <div class="col-4">
                                                    <div class="text-center">
                                                        <a href="{% url 'counselors_portal:login' %}"
                                                            class="appointment-btn w-100">As
                                                            Counselor</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'website/js/main.js' %}"></script>
</body>

</html>