accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('main/', views.main_view, name='main'),
    path('register/', views.register_view, name='register'),
    path('forgot/', views.forgot_view, name='forgot'),
]

clients_portal/urls.py
# clients_portal/urls.py

from django.urls import path
from . import views

app_name = 'clients_portal'

urlpatterns = [
    path('login/', views.clients_login, name='login'),
    path('home/', views.clients_home, name='home'),
    path('viewquiz/', views.view_quiz, name='viewquiz'),
    path('takequiz/', views.take_quiz, name='takequiz'),
    path('takeappointments/', views.take_appointments, name='takeappointments'),
    path('viewappointments/', views.view_appointments, name='viewappointments'),
    path('viewchatbot/', views.chat, name='viewchatbot'),
    path("viewchatbot2", views.chat, name="viewchatbot2"),
    path("ask_question/", views.ask_question, name="ask_question"),
    path("meeting/", views.view_meet, name="meeting"),
    path('viewrecommendations/', views.view_recommendations, name='viewrecommendations'),
    path('allcounselors/', views.all_counselors, name='allcounselors'),
    path('allcounselors/', views.view_payment, name='allcounselors'),
    path('settings/', views.view_settings, name='settings'),
    path('delete_appoint/<int:id>/', views.delete_appoints, name='delete_appoint'),

    # Add more URL patterns as needed
    
    # API
    path('get_user_data/<int:userId>', views.get_user_data, name='get_user_data'),
    path('api/stress_level/', views.stress_level, name='stress_level'),
    path('store_ratings/',views.store_ratings,name='store_ratings'),
    path('api/appointments/', views.appointments_data, name='appointments_data')
]

innercalm/urls.py
# main urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),  # Include website URLs
    path('accounts/', include('accounts.urls')),  # Include accounts URLs
    path('admin_portal/', include('admin_portal.urls')),
    path('clients_portal/', include('clients_portal.urls')),  # Add a trailing slash here
    path('counselors_portal/', include('counselors_portal.urls')),

]


    # Add URLs for other apps here
    # path('admin-portal/', include('admin_portal.urls')),

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('counselors/', views.counselors, name='counselors'),
    path('indcounseling/', views.indcounseling, name='indcounseling'),
    path('gtsessions/', views.gtsessions, name='gtsessions'),
    path('onlinecounseling/', views.onlinecounseling, name='onlinecounseling'),
    path('anxietyquiz/', views.anxietyquiz, name='anxietyquiz'),
    path('contentrecommend/', views.contentrecommend, name='contentrecommend'),
    path('services/', views.services, name='services'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),

]

clients_portal/models.py
from django.db import models

# Create your models here.

clients_portal/views.py
from django.shortcuts import render, redirect,reverse
from accounts.models import User,Client,Counselor,Resources,Quiz,QuizFilled,Appointments,ChatBot,Ratings
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import joblib
from keras.models import load_model
from django.contrib.auth.signals import user_logged_in
from django.core.mail import send_mail
from django.dispatch import receiver
from django.utils.html import format_html
from django.utils.timezone import now
# model = load_model(r"D:\FYP's 2024\Yusra\backend\innercalm\keras_model.h5")


def clients_login(request):
    # Add logic here if needed
    return render(request, 'clients_portal/login.html')

def clients_home(request):
    user=request.user
    counselor=User.objects.filter(is_doc=True).count()
    appoint=Appointments.objects.filter(client=user.id)
    resouces=Resources.objects.all().count()
    appoint_count=Appointments.objects.filter(client=user).count()
    return render(request, 'clients_portal/home.html',{'counselor':counselor,'appoint':appoint,'resouces':resouces,'appoint_count':appoint_count})

def view_quiz(request):
    user=request.user
    data=QuizFilled.objects.filter(user=user)
    return render(request, 'clients_portal/viewquiz.html',{'data':data})

def view_appointments(request):
    user=request.user
    data=Appointments.objects.filter(client=user)
    return render(request, 'clients_portal/viewappointments.html',{'data':data})

def take_appointments(request):
    if request.method=='POST':
        p_name=request.POST.get('p_name')
        p_contact=request.POST.get('p_contact')
        counselor=request.POST.get('counselor')
        client=request.user
        user=User.objects.get(id=counselor)
        reason=request.POST.get('reason')
        duration=request.POST.get('duration')
        type=request.POST.get('a_type')
        time=request.POST.get('time')
        date=request.POST.get('date')
        status='Scheduled'
        appoint=Appointments.objects.create(p_name=p_name,p_contact=p_contact,counselor=user,client=client, reason=reason,duration=duration,type=type,time=time,date=date,status=status)
        if appoint:
            print(appoint)
            send_book_email(appoint)
        return render(request, 'clients_portal/payment.html')
    else:
        data=User.objects.filter(is_doc=True)
        return render(request, 'clients_portal/takeappointments.html',{'data':data})

def view_meet(request):
    if request.method=='POST':
        base_url="https://meet.jit.si/innercalm/"
        msg=request.POST.get('msg')
        url=base_url+msg
        return redirect(url)
    else:
        return render(request, 'clients_portal/meeting.html')

def take_quiz(request):
    if request.method == 'POST':
        total_score=0
        user = request.user
        for question_id, answer in request.POST.items():
            if question_id.startswith('question'):
                question_id = int(question_id.split('_')[1])
                answer = int(answer)
        
                if question_id in [22, 23, 24, 25, 26, 27, 28, 29, 30]:
                    if answer == 1:
                        total_score += 4
                    elif answer == 2:
                        total_score += 3
                    elif answer == 3:
                        total_score += 2
                    elif answer == 4:
                        total_score += 1
                else:
                    if answer == 1:
                        total_score += 1
                    elif answer == 2:
                        total_score += 2
                    elif answer == 3:
                        total_score += 3
                    elif answer == 4:
                        total_score += 4
                    
                question = Quiz.objects.get(pk=question_id)
                print(total_score)
                total=(total_score-30)/90
                print(total)
                if total < 0.25:
                    answer='Low Stress'
                elif total < 0.5:
                    answer='Moderate Stress'
                elif total < 0.75:
                    answer='High Stress'
                else:
                    answer='Severe Stress'
        response = QuizFilled(user=user,stree_value=total, answer=answer)
        response.save()
        return redirect('clients_portal:viewquiz')
    else:
        quiz_questions = Quiz.objects.all()
        return render(request, 'clients_portal/takequiz.html', {'quiz_questions': quiz_questions})

def view_payment(request):
    if request.method=='POST':
        return render(request, 'clients_portal/payment.html')
    else:
        return redirect('home')

def view_recommendations(request):
    models = Resources.objects.all()
    data_init = list(models)
    random.shuffle(data_init)
    data = data_init[:3]
    return render(request, 'clients_portal/viewrecommendations.html', {'data': data})

def all_counselors(request):
    data=User.objects.filter(is_doc=True)
    return render(request, 'clients_portal/allcounselors.html',{'data':data})



def view_settings(request):
    if request.method == 'POST':
        user = request.user
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.age = request.POST.get('age')
        user.phone = request.POST.get('phone')
        user.location = request.POST.get('location')
        user.lang = request.POST.get('lang')
        
        user.save()
        return redirect('clients_portal:home')
    else:
        user=request.user
        return render(request, 'clients_portal/settings.html',{'user':user})


    

# Counselor Data API
def get_user_data(request, userId):
    user = User.objects.get(id=userId)
    counselor = Counselor.objects.get(user=user)

    data = {
        'id': user.id,
        'username': user.username,
        'email': user.email,
        'full_name': f'{counselor.f_name} {counselor.l_name}',
        'qualification': counselor.qualification,
        'specialization': counselor.specialization,
        'age':user.age,
        'gender':user.gender,
        'lang':user.lang,
        'location':user.location,
        'phone':user.phone,
    }

    return JsonResponse(data)


from django.db.models.functions import ExtractMonth
from django.db.models import Sum
from django.db.models import Count
from django.db.models import Avg
def stress_level(request):
    # Query the QuizFilled model to get average stress values grouped by month
    stress_data = QuizFilled.objects.annotate(month=ExtractMonth('created_at')).values('month').annotate(stress_avg=Avg('stree_value'))

    # Initialize data lists
    labels = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    stress_values = [0] * 12  # Initialize with zero values for each month

    # Iterate through the queryset to populate data lists
    for data in stress_data:
        month_index = data['month'] - 1  # Convert month to zero-based index
        stress_values[month_index] = data['stress_avg']

    # Create the projectData dictionary
    projectData = {
        'labels': labels,
        'datasets': [{
            'label': 'Stress',
            'backgroundColor': 'rgba(75, 192, 192, 0.2)',
            'borderColor': 'rgba(75, 192, 192, 1)',
            'borderWidth': 1,
            'data': stress_values
        }]
    }

    # Return the data as JSON response
    return JsonResponse(projectData)
def send_book_email(appoint):
    subject = 'Appointment Booking Notification'
    message = format_html(
        '''
        <p>Dear {},</p>
        <p>Your appointment has been booked successfully.Please visit on  <strong>{}</strong> at <strong>{}</strong>.</p>
        <p>If this was not you, please contact our support immediately.</p>
        <p>Best regards,</p>
        <p>InnerCalm.com</p>
        ''',appoint.p_name, appoint.date, appoint.time
    )

    send_mail(
        subject,
        message,
        'no-reply@example.com',
        [appoint.p_contact],
        html_message=message,
        fail_silently=False,
    )

def delete_appoints(request, id):
    appointments = get_object_or_404(Appointments, id=id)
    appointments.delete()
    return redirect('clients_portal:home')   

import google.generativeai as genai
from django.http import HttpResponseRedirect, JsonResponse
import json

genai.configure(api_key="AIzaSyDtJeLR9T2L9P2ZCVO49j9SDWbFquFK_dI")

def ask_question(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            text = data.get("msg")
            if not text:
                return JsonResponse({"error": "Message content must not be empty"}, status=400)
            
            model = genai.GenerativeModel("gemini-pro")
            chat = model.start_chat()
            response = chat.send_message(text)
            
            user = request.user
            ChatBot.objects.create(text_input=text, gemini_output=response.text, user=user)
            
            response_data = {
                "text": response.text,
            }
            return JsonResponse({"data": response_data})
        except json.JSONDecodeError:
            return JsonResponse({"error": "Invalid JSON"}, status=400)
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)
    else:
        return HttpResponseRedirect(reverse("clients_portal:chat"))
    
def chat(request):
    user = request.user
    chats = ChatBot.objects.filter(user=user)
    return render(request, "clients_portal/viewchatbot.html", {"chats": chats})

def store_ratings(request):
    if request.method == 'POST':
        id=request.POST.get('data_id')
        print(id)
        user = User.objects.get(id=29)

clients_portal/templates/clients_portal/login.html
<!-- website/templates/website/home.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign-In - InnerCalm</title>


    <!-- Favicons -->

    <link rel="stylesheet" href="{% static 'website/img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'website/img/apple-touch-icon.png' %}" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'website/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}">

    <!-- Template Main CSS File -->

    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">


    <style>
        .bg {
            background-color: #f8f9fa;
        }

        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>

<body>



    <div class="my-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card shadow-lg">
                        <div class="card-body p-md-5">
                            <div class="">
                                <div class="row align-items-center">
                                    <div class="col-12 col-sm-12 col-md-5 col-lg-6">
                                        <div class="">
                                            <div class="text-center">
                                                <img src="{% static 'website/img/logowhite2.png' %}" alt="Logo"
                                                    class="img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 col-sm-12 col-md-7 col-lg-6">
                                        <div class="border shadow-lg p-lg-5 p-3 rounded">
                                            <h2 class="text-center">Login</h2>
                                            <form>
                                                <div class="mb-3">
                                                    <label for="username" class="form-label">Username</label>
                                                    <input type="text" id="username" class="form-control"
                                                        placeholder="Enter your username" required>
                                                </div>
                                                <div class="mb-3">
                                                    <label for="password" class="form-label">Password</label>
                                                    <input type="password" id="password" class="form-control"
                                                        placeholder="Enter your password" required>
                                                </div>
                                                <div class="d-flex align-items-center justify-content-between">
                                                    <div class="mb-3 form-check">
                                                        <input type="checkbox" class="form-check-input" id="rememberMe">
                                                        <label class="form-check-label" for="rememberMe">Remember
                                                            Me</label>
                                                    </div>
                                                    <div class="text-end mb-3">
                                                        <a href="{% url 'accounts:forgot' %}"
                                                            class="text-decoration-none">Forgot
                                                            Password?</a>
                                                    </div>
                                                </div>
                                                <div class="text-center">
                                                    <button type="submit"
                                                        class="btn btn-primary w-100 rounded">Login</button>
                                                </div>
                                                <p class="mt-3 text-center">Don't have an account? <a
                                                        href="{% url 'accounts:register' %}"
                                                        class="text-decoration-none">Sign Up</a></p>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'website/js/main.js' %}"></script>
</body>

</html>

clients_portal/templates/clients_portal/payment.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>All Counselors || InnerCalm</title>

    <!-- Favicons -->
    <style>
      body {
        margin-top: 20px;
      }
      .panel-title {
        display: inline;
        font-weight: bold;
      }
      .checkbox.pull-right {
        margin: 0;
      }
      .pl-ziro {
        padding-left: 0px;
      }
    </style>
    <link
      rel="stylesheet"
      href="{% static 'website/img/favicon.png' %}"
      rel="icon"
    />
    <link
      rel="stylesheet"
      href="{% static 'website/img/apple-touch-icon.png' %}"
      rel="apple-touch-icon"
    />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      rel="stylesheet"
      href="{% static 'website/vendor/fontawesome-free/css/all.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'website/vendor/animate.css/animate.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'website/vendor/remixicon/remixicon.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}"
    />

    <!-- Template Main CSS File -->

    <link rel="stylesheet" href="{% static 'website/css/admin_styles.css' %}" />
    <link rel="stylesheet" href="{% static 'website/css/datatables.css' %}" />
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Payment Details</h3>
              <div class="checkbox pull-right">
                <label>
                  <input type="checkbox" />
                  Remember
                </label>
              </div>
            </div>
            <div class="panel-body">
              <form role="form">
                <div class="form-group">
                  <label for="cardNumber"> CARD NUMBER</label>
                  <div class="input-group">
                    <input
                      type="text"
                      class="form-control"
                      id="cardNumber"
                      placeholder="Valid Card Number"
                      required
                      autofocus
                    />
                    <span class="input-group-addon"
                      ><span class="glyphicon glyphicon-lock"></span
                    ></span>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-7 col-md-7">
                    <div class="form-group">
                      <label for="expityMonth"> EXPIRY DATE</label>
                      <div class="col-xs-6 col-lg-6 pl-ziro">
                        <input
                          type="text"
                          class="form-control"
                          id="expityMonth"
                          placeholder="MM"
                          required
                        />
                      </div>
                      <div class="col-xs-6 col-lg-6 pl-ziro">
                        <input
                          type="text"
                          class="form-control"
                          id="expityYear"
                          placeholder="YY"
                          required
                        />
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-5 col-md-5 pull-right">
                    <div class="form-group">
                      <label for="cvCode"> CV CODE</label>
                      <input
                        type="password"
                        class="form-control"
                        id="cvCode"
                        placeholder="CV"
                        required
                      />
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <ul class="nav nav-pills nav-stacked">
            <li class="active">
              <a href="#"
                ><span class="badge pull-right"
                  ><span class="glyphicon glyphicon-usd"></span>4200</span
                >
                Final Payment</a
              >
            </li>
          </ul>
          <br />
          <a
            href="http://127.0.0.1:8000/clients_portal/home/"
            class="btn btn-success btn-lg btn-block"
            role="button"
            >Pay</a
          >
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="{% static 'website/js/app.js' %}"></script>
    <script src="{% static 'website/js/datatables.js' %}"></script>
    <script src="{% static 'website/js/jquery.multiselect.js' %}"></script>
    <script src="{% static 'website/js/bootstrap.bundle.min.js' %}"></script>

    <!-- <script>
        toggleButton.onclick = function () {
            el.classList.toggle("toggled");
        };
    </script> -->
    <script>
      const getUserDataUrl =
        "{% url 'clients_portal:get_user_data' userId=0 %}";
    </script>

    <script>
      function loadUserData(userId) {
        $.ajax({
          url: getUserDataUrl + userId,
          type: "GET",
          success: function (data) {
            $("#viewModalLabel").text("Details for " + data.full_name);
            $("#modal-body-username").text("Username: " + data.username);
            $("#modal-body-email").text("Email: " + data.email);
            $("#modal-body-age").text("Age: " + data.age);
            $("#modal-body-gender").text("Gender: " + data.gender);
            $("#modal-body-lang").text("Language: " + data.lang);
            $("#modal-body-location").text("Location: " + data.location);
            $("#modal-body-phone").text("Phone: " + data.phone);
            $("#viewModal").modal("show");
          },
          error: function (xhr, status, error) {
            console.error(error);
          },
        });
      }
    </script>

    <script type="text/javascript">
      $(document).ready(function () {
        $("#counselor-table").DataTable({
          language: {
            paginate: {
              previous: '<i class="fa-solid fa-chevron-left p-5px"></i>',
              next: '<i class="fa-solid fa-chevron-right p-5px"></i>',
            },
            lengthMenu: "",
            search: "",
            searchPlaceholder: "Search...",
          },

          ordering: true,
        });
      });
    </script>
  </body>
</html>