accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('main/', views.main_view, name='main'),
    path('register/', views.register_view, name='register'),
    path('forgot/', views.forgot_view, name='forgot'),
]

admin_portal/urls.py
from django.urls import path
from . import views

app_name = 'admin_portal'

urlpatterns = [
    path('home/', views.admin_home, name='home'),
    path('alluser/', views.all_users, name='alluser'),
    path('allappointments/', views.all_appointments, name='allappointments'),
    path('allcounselors/', views.all_counselors, name='allcounselors'),
    path('addcounselors/', views.add_counselors, name='addcounselors'),
    path('store_counselor/', views.store_counselor, name='store_counselor'),
    path('delete_counselor/<int:id>/', views.delete_counselor, name='delete_counselor'),
    path('allresources/', views.all_resources, name='allresources'),
    path('viewanalytics/', views.view_analytics, name='viewanalytics'),
    path('allreports/', views.all_report, name='allreports'),
    path('settings/', views.view_settings, name='settings'), 
    # Add more URL patterns as needed
    path('form_index', views.home, name='form_index'),
    path('user-post/', views.userPost, name='user-post'),
    path('topic/<int:pk>/', views.postTopic, name='topic-detail'),
    path('search-result/', views.searchView, name='search-result'),
    path('user-dashboard/', views.userDashboard, name='user-dashboard'),
    path('upvote/', views.upvote, name='upvote'),
    path('downvote/', views.downvote, name='downvote'),
    path('blog/', views.blogListView, name='blog'),
    path('article/<slug:slug>/', views.blogDetailView, name='article-detail'),
]

innercalm/urls.py
# main urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),  # Include website URLs
    path('accounts/', include('accounts.urls')),  # Include accounts URLs
    path('admin_portal/', include('admin_portal.urls')),
    path('clients_portal/', include('clients_portal.urls')),  # Add a trailing slash here
    path('counselors_portal/', include('counselors_portal.urls')),

]


    # Add URLs for other apps here
    # path('admin-portal/', include('admin_portal.urls')),

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('counselors/', views.counselors, name='counselors'),
    path('indcounseling/', views.indcounseling, name='indcounseling'),
    path('gtsessions/', views.gtsessions, name='gtsessions'),
    path('onlinecounseling/', views.onlinecounseling, name='onlinecounseling'),
    path('anxietyquiz/', views.anxietyquiz, name='anxietyquiz'),
    path('contentrecommend/', views.contentrecommend, name='contentrecommend'),
    path('services/', views.services, name='services'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),

]

admin_portal/models.py
from django.db import models

# Create your models here.

admin_portal/forms.py
from django import forms
from accounts.models import User

class CounselorForm(forms.Form):
    fname = forms.CharField(label='First Name', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter first name'}))
    lname = forms.CharField(label='Last Name', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter last name'}))
    username = forms.CharField(label='Username', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter username'}))
    email = forms.EmailField(label='Email', max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter password'}))
    phone = forms.CharField(label='Phone Number', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter phone number'}))
    qual = forms.CharField(label='Qualifications', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter qualifications'}))
    spec = forms.CharField(label='Specialties', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter specialties'}))
    location = forms.ChoiceField(label='Location', choices=[('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Karachi', 'Karachi'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Rawalpindi', 'Rawalpindi')], widget=forms.Select(attrs={'class': 'form-select', 'aria-label': 'Default select example'}))
    gender = forms.ChoiceField(label='Gender', choices=[('male', 'Male'), ('female', 'Female')], widget=forms.Select(attrs={'class': 'form-select', 'aria-label': 'Default select example'}))
    age = forms.CharField(label='Age', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter age'}))
    image = forms.ImageField(label='Profile Picture', required=False)

from accounts.models import *

class UserPostForm(forms.ModelForm):

    title = forms.CharField(label="", widget=forms.TextInput(attrs={
        'class':'form-control form-control-style-3',
        'placeholder':'Title',
    }))

    description = forms.CharField(label="", widget=forms.Textarea(attrs={
        'class':'form-control form-control-style-3',
        'placeholder':'Description in detail...',
        'rows':'8',
        'cols':'80',
    }))

    class Meta:
        model = UserPost
        fields = ['title', 'description']

class AnswerForm(forms.ModelForm):

    content = forms.CharField(label="", widget=forms.Textarea(attrs={
        'class':'form-control form-control-style-3',
        'placeholder':'Write your answer...',
        'rows':'8',
        'cols':'50',
    }))

    class Meta:
        model = Answer
        fields = ['content',]

admin_portal/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from accounts.models import User, Client, Counselor, Resources, Appointments,Author
from accounts.models import *
from django.contrib.auth.hashers import make_password
from .forms import UserPostForm, AnswerForm
from django.template.loader import render_to_string

from .forms import CounselorForm
@login_required
def admin_home(request):
    user_count = User.objects.count()
    appoint_count = Appointments.objects.count()
    res_count=Resources.objects.count()
    return render(request, 'admin_portal/home.html', {'user_count': user_count, 'appoint_count': appoint_count, 'res_count': res_count})
@login_required
def all_users(request):
    users=User.objects.all()
    return render(request, 'admin_portal/alluser.html',{'users':users})
    
@login_required
def all_appointments(request):
    appoint=Appointments.objects.all()
    return render(request, 'admin_portal/allappointments.html',{'appoint':appoint})
@login_required
def all_counselors(request):
    data=User.objects.filter(is_doc=True)
    return render(request, 'admin_portal/allcounselors.html',{'data':data})
@login_required
def add_counselors(request):
    form = CounselorForm()
    return render(request, 'admin_portal/addcounselor.html',{'form': form})

def store_counselor(request):
    if request.method == 'POST':
        form = CounselorForm(request.POST,request.FILES)
        if form.is_valid():
            f_name = form.cleaned_data['fname']
            l_name = form.cleaned_data['lname']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            phone = form.cleaned_data['phone']
            qual = form.cleaned_data['qual']
            spec = form.cleaned_data['spec']
            location = form.cleaned_data['location']
            gender = form.cleaned_data['gender']
            age = form.cleaned_data['age']
            image = form.cleaned_data['image']
            is_doc=True
            user = User.objects.create_user(
            username=username,
            password=password,
            email=email,
            is_doc=True
            )
            user.save()
            counselor_instance = Counselor.objects.create(
                user=user,
                f_name=f_name,
                l_name=l_name,
                specialization=spec,
                qualification=qual,
                image=image
            )
            counselor_instance.save()
            author_inst=Author.objects.create(
                user=user
            )
            author_inst.save()
    return redirect('admin_portal:home')

def delete_counselor(request, id):
    counselor = get_object_or_404(Counselor, user_id=id) 
    u_id=counselor.user.id
    counselor.delete()
    user = get_object_or_404(User, id=u_id)
    user.delete()
    return redirect('admin_portal:home')    


    

# def store_counselor(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         raw_password = request.POST.get('password')
#         f_name = request.POST.get('f_name')
#         l_name = request.POST.get('l_name')
#         specialization = request.POST.get('spec')
#         qualification = request.POST.get('qual')
#         email = request.POST.get('email')
#         phone = request.POST.get('phone')
#         location = request.POST.get('location')
#         age = request.POST.get('age')
#         gender = request.POST.get('gender')
#         password = make_password(raw_password)
#         user = User.objects.create_user(
#             username=username,
#             password=password,
#             email=email,
#             is_doc=True
#         )
#         user.phone = phone
#         user.age = age
#         user.location = location
#         user.gender = gender
#         user.is_active = True
#         user.save()
#         Counselor.objects.create(
#             user=user,
#             f_name=f_name,
#             l_name=l_name,
#             specialization=specialization,
#             qualification=qualification
#         )
#         return render(request, 'admin_portal/addcounselor.html')
#     else:
#         return render(request, 'admin_portal/addcounselor.html')
@login_required
def all_resources(request):
    data=Resources.objects.all()
    return render(request, 'admin_portal/allresources.html',{'data':data})
@login_required
def all_report(request):
    # Add logic here if needed
    return render(request, 'admin_portal/allreport.html')
@login_required
def view_analytics(request):
    # Add logic here if needed
    return render(request, 'admin_portal/viewanalytics.html')
@login_required
def view_settings(request):
    user=request.user
    if request.method == 'POST':
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.phone = request.POST.get('phone')
        user.location = request.POST.get('location')
        user.age = request.POST.get('age')
        user.lang = request.POST.get('lang')
        user.save()
        return redirect('admin_portal:home')
    return render(request, 'admin_portal/settings.html',{'user':user})

# Form

def home(request):
    user_posts = UserPost.objects.all()
    
    # Display latest posts.
    latest_blogs = BlogPost.objects.order_by('-timestamp')[0:3]

    latest_topics = UserPost.objects.order_by('-date_created')[0:3]
    
    context = {
        'user_posts':user_posts,
        'latest_blogs':latest_blogs,
        'latest_topics':latest_topics
    }
    return render(request, 'form/forum-main.html', context)

@login_required
def userPost(request):
    # User Post form.
    form = UserPostForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            author=request.user.author
            if author:
                title = request.POST.get('title')
                description = request.POST.get('description')
                topic = UserPost.objects.create(title=title, author=request.user.author, description=description)
                topic.save()
                return redirect('admin_portal:form_index')
            else:
                form = UserPostForm()
                context = {'form':form}
                return render(request, 'form/user-post.html', context)
    else:
        form = UserPostForm()

    context = {'form':form}
    return render(request, 'form/user-post.html', context)

@login_required(login_url='login')
def postTopic(request, pk):
    # Get specific user post by id.
    post_topic = get_object_or_404(UserPost, pk=pk)

    # Count Post View only for authenticated users
    if request.user.is_authenticated:
        TopicView.objects.get_or_create(user=request.user, user_post=post_topic)

    # Get all answers of a specific post.
    answers = Answer.objects.filter(user_post = post_topic)

    # Answer form.
    answer_form = AnswerForm(request.POST or None)
    if request.method == "POST":
        if answer_form.is_valid():
            content = request.POST.get('content')
            # passing User Id & User Post Id to DB
            ans = Answer.objects.create(user_post=post_topic, user=request.user, content=content)
            ans.save()
            return HttpResponseRedirect(post_topic.get_absolute_url())
    else:
        answer_form = AnswerForm()
    
    context = {
        'topic':post_topic,
        'answers':answers,
        'answer_form':answer_form,
        
    }
    return render(request, 'form/topic-detail.html', context)

@login_required(login_url='login')
def userDashboard(request):
    topic_posted = request.user.author.userpost_set.all()
    ans_posted = request.user.answer_set.all()
    topic_count = topic_posted.count()
    ans_count = ans_posted.count()
    
    context = {
        'topic_posted':topic_posted,
        'ans_posted':ans_posted,
        'topic_count':topic_count,
        'ans_count':ans_count
    }
    return render(request, 'form/user-dashboard.html', context)

def searchView(request):
    queryset = UserPost.objects.all()
    search_query = request.GET.get('q')

    if search_query:
        queryset = queryset.filter(
            Q(title__icontains=search_query) | Q(description__icontains=search_query) 
        ).distinct()
        
        q_count = queryset.count()
    else:
        messages.error(request, f"Oops! Looks like you didn't put any keyword. Please try again.")
        return redirect('admin_portal:form_index')

    
    context = {
        'queryset':queryset,
        'search_query':search_query,
        'q_count':q_count
    }

    return render(request, 'form/search-result.html', context)


def upvote(request):
    answer = get_object_or_404(Answer, id=request.POST.get('answer_id'))
    
    has_upvoted = False

    if answer.upvotes.filter(id = request.user.id).exists():
        answer.upvotes.remove(request.user)
        has_upvoted = False        
    else:
        answer.upvotes.add(request.user)
        answer.downvotes.remove(request.user)
        has_upvoted = True

    return HttpResponseRedirect(answer.user_post.get_absolute_url())
    

def downvote(request):
    answer = get_object_or_404(Answer, id=request.POST.get('answer_id'))
    
    has_downvoted = False
    
    if answer.downvotes.filter(id = request.user.id).exists():
        answer.downvotes.remove(request.user)
        has_downvoted = False
    else:
        answer.downvotes.add(request.user)
        answer.upvotes.remove(request.user)
        has_downvoted = True
    
    return HttpResponseRedirect(answer.user_post.get_absolute_url())

# Blog listing page view.
def blogListView(request):
    
    # Display all blog posts.
    all_posts = BlogPost.objects.all()
    
    context = {
        'all_posts':all_posts
    }

admin_portal/templates/form/base.html
{% include "form/header.html" %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-12">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
</div>

{% endblock content %}

{% include "form/footer.html" %}

admin_portal/templates/form/footer.html
{% load static %}


</div>


<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 footer-contact">
                    <h1 class="flogo me-auto">
                        <a href="{% url 'website:home' %}" class="flogo me-auto">
                            <img src="{% static 'website/img/blacklogo2.png' %}" alt="" class="img-fluid">
                        </a>
                    </h1>
                    <p>
                        Comsats University Islamabad <br> Wah Campus
                        Wah Cantt, Pakistan <br><br>
                        <strong>Phone:</strong> +92 340 1417862<br>
                        <strong>Email:</strong> info@innercalm.com<br>
                    </p>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:home' %}">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:about' %}">About us</a>
                        </li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:services' %}">Services</a>
                        </li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:services' %}">Terms of
                                service</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:services' %}">Privacy
                                policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:indcounseling' %}">Individual
                                Counseling</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:gtsessions' %}">Group
                                Therapy
                                Sessions</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:gtsessions' %}">Cognitive
                                Behavioral Therapy (CBT)</a>
                        </li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:gtsessions' %}">Mindfulness
                                Meditation</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:gtsessions' %}">Stress
                                Management Workshops</a></li>
                    </ul>
                </div>


                <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4>Join Our Newsletter</h4>
                    <p>Subscribe to our newsletter to receive updates and news.</p>
                    <form action="#" method="post">
                        <input type="email" name="email" placeholder="Your Email" required><input type="submit"
                            value="Subscribe">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="container d-md-flex py-4">

        <div class="me-md-auto text-center text-md-start">
            <div class="copyright">
                &copy; Copyright <strong><span>InnerCalm</span></strong>. All Rights Reserved
            </div>
        </div>
        <div class="social-links text-center text-md-right pt-3 pt-md-0">
            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
    </div>
</footer><!-- End Footer -->

<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<script src="{% static 'website/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'website/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'website/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'website/vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'website/js/main.js' %}"></script>



<!-- START: Scripts -->

<!-- Object Fit Images -->
<script src="{% static 'vendor/object-fit-images/dist/ofi.min.js' %}"></script>

<!-- Popper -->
<script src="{% static 'vendor/popper.js/dist/umd/popper.min.js' %}"></script>

<!-- Bootstrap -->
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>

<!-- Fancybox -->
<script src="{% static 'vendor/fancybox/dist/jquery.fancybox.min.js' %}"></script>

<!-- Cleave -->
<script src="{% static 'vendor/cleave.js/dist/cleave.min.js' %}"></script>

<!-- Validator -->
<script src="{% static 'vendor/validator/validator.min.js' %}"></script>

<!-- Sticky Kit -->
<script src="{% static 'vendor/sticky-kit/dist/sticky-kit.min.js' %}"></script>

<!-- Jarallax -->
<script src="{% static 'vendor/jarallax/dist/jarallax.min.js' %}"></script>
<script src="{% static 'vendor/jarallax/dist/jarallax-video.min.js' %}"></script>

<!-- Isotope -->
<script src="{% static 'vendor/isotope-layout/dist/isotope.pkgd.min.js' %}"></script>

<!-- ImagesLoaded -->
<script src="{% static 'vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>

<!-- Swiper -->
<script src="{% static 'vendor/swiper/dist/js/swiper.min.js' %}"></script>

<!-- Gist Embed -->
<script src="{% static 'vendor/gist-embed/gist-embed.min.js' %}"></script>

<!-- Bootstrap Select -->
<script src="{% static 'vendor/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>

<!-- Dropzone -->
<script src="{% static 'vendor/dropzone/dist/min/dropzone.min.js' %}"></script>

<!-- Quill -->
<script src="{% static 'vendor/quill/dist/quill.min.js' %}"></script>

</body>

</html>

admin_portal/templates/form/header.html
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Community Forum for People to Discuss</title>

    <meta name="description" content="Amdesk - Help Center HTML template for your digital products">
    <meta name="keywords" content="helpdesk, forum, template, HTML template, responsive, clean">
    <meta name="author" content="nK">

    <link rel="icon" type="image/png" href="assets/images/favicon.png">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- START: Styles -->

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,600,700%7cMaven+Pro:400,500,700"
        rel="stylesheet"><!-- %7c -->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/dist/css/bootstrap.min.css' %}">

    <!-- Fancybox -->
    <link rel="stylesheet" href="{% static 'vendor/fancybox/dist/jquery.fancybox.min.css' %}">

    <!-- Pe icon 7 stroke -->
    <link rel="stylesheet"
        href="{% static 'vendor/pixeden-stroke-7-icon/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css' %}">

    <!-- Swiper -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/swiper/dist/css/swiper.min.css' %}">

    <!-- Bootstrap Select -->
    <link rel="stylesheet" type="text/css"
        href="{% static 'vendor/bootstrap-select/dist/css/bootstrap-select.min.css' %}">

    <!-- Dropzone -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/dropzone/dist/min/dropzone.min.css' %}">

    <!-- Quill -->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/quill/dist/quill.snow.css' %}">

    <!-- Font Awesome -->
    <script defer src="{% static 'vendor/fontawesome-free/js/all.js' %}"></script>
    <script defer src="{% static 'vendor/fontawesome-free/js/v4-shims.js' %}"></script>

    <!-- Amdesk -->
    <link rel="stylesheet" href="{% static 'css/amdesk.min.css' %}">

    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- END: Styles -->

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>



    <!-- Favicons -->

    <link rel="stylesheet" href="{% static 'website/img/favicon.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'website/img/apple-touch-icon.png' %}" rel="apple-touch-icon">


    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">


    <!-- Vendor CSS Files -->
    <link rel="stylesheet" href="{% static 'website/vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/animate.css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/glightbox/css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'website/vendor/swiper/swiper-bundle.min.css' %}">

    <!-- Template Main CSS File -->

    <link rel="stylesheet" href="{% static 'website/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'website/css/styles.css' %}">


</head>

<body>


    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-flex align-items-center fixed-top">
        <div class="container d-flex justify-content-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope"></i> <a href="mailto:contact@innercalm.com">contact@innercalm.com</a>
                <i class="bi bi-phone"></i> +92 340 1417862
            </div>
            <div class="d-none d-lg-flex social-links align-items-center">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto">
                <a href="{% url 'website:home' %}" class="logo me-auto">
                    <img src="{% static 'website/img/blacklogo2.png' %}" alt="" class="img-fluid">
                </a>
            </h1>

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto" href="{% url 'website:home' %}">Home</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'website:about' %}">About</a></li>
                    <li class="dropdown">
                        <a class="active" href="{% url 'admin_portal:form_index' %}"><span>Forms</span> <i
                                class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="{% url 'admin_portal:form_index' %}">Froms Community</a></li>
                            {% if user.is_authenticated  %}
                            <li><a href="{% url 'admin_portal:user-post' %}">Post New Topic</a></li>
                            {% endif %}
                            

                        </ul>
                    </li>
                    <li><a class="nav-link scrollto" href="{% url 'website:counselors' %}">Counselors</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'website:services' %}">Our Services</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'website:contact' %}">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="appointment-btn scrollto"><span
                    class="d-none d-md-inline">Logout</span></a>
            {% else %}
            <a href="{% url 'accounts:main' %}" class="appointment-btn scrollto"><span
                    class="d-none d-md-inline">Login</span></a>
            {% endif %}


        </div>
    </header><!-- End Header -->